# WIP
version: "3"
services:
  # app:
  #   build: .
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "3000:3000"
  #     - "9229:9229"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres:/var/lib/postgresql/data
# volumes:
#   postgres:
